# Non-IID Pair-Feature 结果

这个 notebook 在重新生成的 nonrenewal 轨迹上评估已经训练好的三能级 non-IID pair-feature 估计器。
这里的 bCRB 诊断使用一阶马尔可夫 waiting-time 公式：先由 kernel matrix 解析构造平稳 `mu_theta(tau)`、相邻 pair joint 和 `q_theta(tau'|tau)`，再计算 `J_init + (N-1) J_pair`。代码不对截断后的 pair density 或 `q` 做事后重归一化；CSV 里的 capture area 是数值积分误差诊断。

In [1]:
%run ../scripts/evaluate_noniid_results.py

project_root = /home/t30/rab/ge48zus/paramest-nn/ParamEst-NN-main
data_root = /home/t30/rab/ge48zus/paramest-nn/ParamEst-NN-main/data
output_root = /home/t30/rab/ge48zus/paramest-nn/ParamEst-NN-main/data/result_noniid
models = ('v', 'shelving', 'lambda', 'ladder')
device = cpu
batch_size = 8192
max_eval_traj = all validation

[v] loading checkpoint and data

/home/t30/rab/ge48zus/paramest-nn/ParamEst-NN-main/scripts/evaluate_noniid_results.py:866: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  ckpt = torch.load(ckpt_path, map_location="cpu")

[v] val rows = 200,202, lengths = [10, 15, 20, 30, 40, 50]

[v] bounds block=1/6 L=50 analytic learned/bCRB trace ratio=1.26

[v] bounds block=2/6 L=50 analytic learned/bCRB trace ratio=2.43

[v] bounds block=3/6 L=50 analytic learned/bCRB trace ratio=1.65

[v] bounds block=4/6 L=50 analytic learned/bCRB trace ratio=1.22

[v] bounds block=5/6 L=50 analytic learned/bCRB trace ratio=1.06

[v] bounds block=6/6 L=50 analytic learned/bCRB trace ratio=1.01
[v] L=50 RMSE = 0.759006679058075 0.6634736061096191

[shelving] loading checkpoint and data
[shelving] val rows = 200,203, lengths = [10, 15, 20, 30, 40, 50]

[shelving] bounds block=1/6 L=50 analytic learned/bCRB trace ratio=1.98

[shelving] bounds block=2/6 L=50 analytic learned/bCRB trace ratio=0.248

[shelving] bounds block=3/6 L=50 analytic learned/bCRB trace ratio=2.42

[shelving] bounds block=4/6 L=50 analytic learned/bCRB trace ratio=2.89

[shelving] bounds block=5/6 L=50 analytic learned/bCRB trace ratio=0.2

[shelving] bounds block=6/6 L=50 analytic learned/bCRB trace ratio=1.25
[shelving] L=50 RMSE = 0.7571477890014648 0.678527295589447

[lambda] loading checkpoint and data
[lambda] val rows = 200,204, lengths = [10, 15, 20, 30, 40, 50]

[lambda] bounds block=1/6 L=50 analytic learned/bCRB trace ratio=1.49

[lambda] bounds block=2/6 L=50 analytic learned/bCRB trace ratio=1.25

[lambda] bounds block=3/6 L=50 analytic learned/bCRB trace ratio=1.03

[lambda] bounds block=4/6 L=50 analytic learned/bCRB trace ratio=1.21

[lambda] bounds block=5/6 L=50 analytic learned/bCRB trace ratio=1.15

[lambda] bounds block=6/6 L=50 analytic learned/bCRB trace ratio=1.23
[lambda] L=50 RMSE = 0.7401596307754517 0.6856282353401184

[ladder] loading checkpoint and data
[ladder] val rows = 200,194, lengths = [10, 15, 20, 30, 40, 50]

[ladder] bounds block=1/6 L=50 analytic learned/bCRB trace ratio=0.219

[ladder] bounds block=2/6 L=50 analytic learned/bCRB trace ratio=1.13

[ladder] bounds block=3/6 L=50 analytic learned/bCRB trace ratio=1.12

[ladder] bounds block=4/6 L=50 analytic learned/bCRB trace ratio=1.29

[ladder] bounds block=5/6 L=50 analytic learned/bCRB trace ratio=0.211

[ladder] bounds block=6/6 L=50 analytic learned/bCRB trace ratio=0.464
[ladder] L=50 RMSE = 0.7254746556282043 0.7855497002601624

Saved:
  /home/t30/rab/ge48zus/paramest-nn/ParamEst-NN-main/data/result_noniid/noniid_pair_validation_by_length.csv
  /home/t30/rab/ge48zus/paramest-nn/ParamEst-NN-main/data/result_noniid/noniid_pair_validation_summary.csv
  /home/t30/rab/ge48zus/paramest-nn/ParamEst-NN-main/data/result_noniid/noniid_pair_learned_probes.csv
  /home/t30/rab/ge48zus/paramest-nn/ParamEst-NN-main/data/result_noniid/noniid_pair_sequence_bcrb.csv
  /home/t30/rab/ge48zus/paramest-nn/ParamEst-NN-main/data/result_noniid/figures

Summary:
   model                                                                                              checkpoint sampling_mode  n_eval  L_max  best_val_std_mse  rmse_delta_Lmax  rmse_omega_Lmax  K_one  M_pair  feature_dim
  ladder     /home/t30/rab/ge48zus/paramest-nn/ParamEst-NN-main/data/models/ladder/noniid_pair_laplace_ladder.pt        noniid  200194     50          0.585025         0.725475         0.785550      4       4           18
  lambda     /home/t30/rab/ge48zus/paramest-nn/ParamEst-NN-main/data/models/lambda/noniid_pair_laplace_lambda.pt        noniid  200204     50          0.564740         0.740160         0.685628      4       4           18
shelving /home/t30/rab/ge48zus/paramest-nn/ParamEst-NN-main/data/models/shelving/noniid_pair_laplace_shelving.pt        noniid  200203     50          0.582128         0.757148         0.678527      4       4           18
       v               /home/t30/rab/ge48zus/paramest-nn/ParamEst-NN-main/data/models/v/noniid_pair_laplace_v.pt        noniid  200202     50          0.583919         0.759007         0.663474      4       4           18

In [2]:
RESULTS["summary_df"]

,model,checkpoint,sampling_mode,n_eval,L_max,best_val_std_mse,rmse_delta_Lmax,rmse_omega_Lmax,K_one,M_pair,feature_dim
3,ladder,/home/t30/rab/ge48zus/paramest-nn/ParamEst-NN-...,noniid,200194,50,0.585025,0.725475,0.785550,4,4,18
2,lambda,/home/t30/rab/ge48zus/paramest-nn/ParamEst-NN-...,noniid,200204,50,0.564740,0.740160,0.685628,4,4,18
1,shelving,/home/t30/rab/ge48zus/paramest-nn/ParamEst-NN-...,noniid,200203,50,0.582128,0.757148,0.678527,4,4,18
0,v,/home/t30/rab/ge48zus/paramest-nn/ParamEst-NN-...,noniid,200202,50,0.583919,0.759007,0.663474,4,4,18

In [3]:
RESULTS["length_df"].head(20)

     L  n_eval  rmse_delta  rmse_omega  elapsed_s     model
18  10  200194    0.795452    1.037515   3.569710    ladder
19  15  200194    0.765883    0.938272   3.569710    ladder
20  20  200194    0.751214    0.886659   3.569710    ladder
21  30  200194    0.736886    0.831746   3.569710    ladder
22  40  200194    0.729725    0.803515   3.569710    ladder
23  50  200194    0.725475    0.785550   3.569710    ladder
12  10  200204    0.819951    1.014695   3.865651    lambda
13  15  200204    0.787711    0.891748   3.865651    lambda
14  20  200204    0.770637    0.823435   3.865651    lambda
15  30  200204    0.754087    0.749473   3.865651    lambda
16  40  200204    0.745311    0.710436   3.865651    lambda
17  50  200204    0.740160    0.685628   3.865651    lambda
6   10  200203    0.820259    1.011565   3.328802  shelving
7   15  200203    0.794230    0.887685   3.328802  shelving
8   20  200203    0.781415    0.818735   3.328802  shelving
9   30  200203    0.767747    0.744213   3.328802  shelving
10  40  200203    0.761079    0.702950   3.328802  shelving
11  50  200203    0.757148    0.678527   3.328802  shelving
0   10  200202    0.819197    0.982747   5.556586         v
1   15  200202    0.793407    0.860474   5.556586         v

In [4]:
RESULTS["bound_df"].head(20)

,model,block_id,L,n_eval,grid_size,tau_max,delta,omega,mse_delta,mse_omega,...,fisher_pair_01,fisher_pair_11,capture_area_pair,capture_area_mu,q_row_area_min,q_row_area_max,transition_col_sum_min,transition_col_sum_max,grid_transition_col_sum_min,grid_transition_col_sum_max
18,ladder,0,50,384,2048,1024.0,1.019593,4.302778,0.136818,0.498487,...,1.039386,15.607402,0.973906,0.986860,0.985863,1.029911,1.0,1.0,0.985863,1.040949
19,ladder,1,50,384,2048,1024.0,0.272011,0.789400,0.838691,2.586530,...,0.370446,10.808582,1.004162,1.002081,0.999833,1.010179,1.0,1.0,0.999833,1.021159
20,ladder,2,50,384,2048,1024.0,1.365011,0.949927,0.058674,0.817944,...,1.159953,4.664634,1.001197,1.000598,0.999750,1.002264,1.0,1.0,0.999750,1.021294
21,ladder,3,50,384,2048,1024.0,2.549374,1.185668,0.314721,0.098534,...,0.449478,2.478597,1.000187,1.000094,0.999582,1.001419,1.0,1.0,0.999582,1.021564
22,ladder,4,50,384,2048,1024.0,1.434279,3.458289,0.032513,0.171524,...,1.515354,11.213524,0.990523,0.995248,0.994192,1.022432,1.0,1.0,0.994192,1.029680
23,ladder,5,50,384,2048,1024.0,2.492319,3.877595,1.063286,0.359827,...,1.518444,8.245685,0.982917,0.991417,0.990324,1.025850,1.0,1.0,0.990324,1.034954
12,lambda,0,50,384,2048,640.0,0.996590,4.105146,0.169978,0.413556,...,0.576452,9.215010,0.997783,0.998891,0.998705,0.998921,1.0,1.0,0.998705,1.000011
13,lambda,1,50,384,2048,640.0,1.010209,4.546531,0.157709,0.965618,...,0.519156,9.073051,0.997067,0.998532,0.998287,0.998572,1.0,1.0,0.998287,1.000010
14,lambda,2,50,384,2048,640.0,1.768436,4.698548,0.154227,1.173348,...,0.878213,9.149383,0.996740,0.998369,0.998096,0.998413,1.0,1.0,0.998096,1.000010
15,lambda,3,50,384,2048,640.0,2.040307,1.680770,0.251539,0.263352,...,0.601304,2.431170,0.999707,0.999854,0.999828,0.999859,1.0,1.0,0.999828,1.000013
16,lambda,4,50,384,2048,640.0,2.495539,3.713449,1.047306,0.320161,...,0.937783,5.519818,0.998246,0.999122,0.998975,0.999146,1.0,1.0,0.998975,1.000011
17,lambda,5,50,384,2048,640.0,0.439578,3.479112,0.881923,0.176003,...,0.353699,10.960473,0.998548,0.999274,0.999152,0.999294,1.0,1.0,0.999152,1.000012
6,shelving,0,50,384,2048,1024.0,0.853398,2.327793,0.222267,0.195883,...,0.780270,8.399007,0.995628,0.997812,0.997438,0.997869,1.0,1.0,0.997438,1.000052
7,shelving,1,50,384,2048,1024.0,0.931080,4.663624,0.252348,1.217843,...,0.386054,7.691284,0.948170,0.973750,0.969367,0.974420,1.0,1.0,0.969367,1.000052
8,shelving,2,50,384,2048,1024.0,1.279502,2.805386,0.037120,0.163958,...,0.966142,8.169599,0.992750,0.996369,0.995755,0.996464,1.0,1.0,0.995755,1.000052
9,shelving,3,50,384,2048,1024.0,2.021579,0.462328,0.031133,0.070929,...,-2.180235,10.629733,0.999872,0.999936,0.999917,0.999937,1.0,1.0,0.999917,1.000052
10,shelving,4,50,384,2048,1024.0,1.369891,4.564046,0.024936,1.040268,...,0.691455,9.126885,0.953341,0.976400,0.972458,0.977001,1.0,1.0,0.972458,1.000052
11,shelving,5,50,384,2048,1024.0,1.777231,0.858610,0.022432,0.290204,...,-0.246267,2.168311,0.999515,0.999758,0.999709,0.999764,1.0,1.0,0.999709,1.000052
0,v,0,50,384,2048,320.0,2.161258,4.042981,0.535497,0.407895,...,1.791877,12.811283,0.999919,0.999960,0.999956,1.000385,1.0,1.0,0.999956,1.002107
1,v,1,50,384,2048,320.0,1.090421,3.354240,0.078495,0.120160,...,1.556419,18.768525,0.999948,0.999974,0.999971,1.000389,1.0,1.0,0.999971,1.002084